services:
  db:
    image: postgres:15-alpine
    restart: always
    container_name: rede_excedente-db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    networks:
      - rede_excedente
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    image: rede_excedente-backend
    container_name: rede_excedente-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - PYTHONPATH=/app/src
    depends_on:
      - db
    networks:
        - rede_excedente
    working_dir: /app/src
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

  frontend:
    build: ./frontend
    image: rede_excedente-frontend
    container_name: rede_excedente-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - rede_excedente
    environment:
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true

volumes:
  postgres_data:

networks:
  rede_excedente:
    name: rede_excedente
    driver: bridge